# Agent Conversation Coordinator Configuration

# Agent settings
agents:
  agent_a:
    name: "Nova"
    id: "agent_a"
    color: "cyan"
    model: "claude-sonnet-4-5-20250929"
    max_tokens: 8000  # Must be greater than thinking_budget (5000)
  agent_b:
    name: "Atlas"
    id: "agent_b"
    color: "yellow"
    model: "claude-sonnet-4-5-20250929"
    max_tokens: 8000  # Must be greater than thinking_budget (5000)

# Conversation settings
conversation:
  max_turns: 20  # Maximum number of exchanges before stopping
  initial_prompt: "What do you think about the future of AI agents working together autonomously?"
  turn_delay: 1.0  # Seconds to wait between turns (for readability)

  # Extended thinking feature
  show_thinking: true  # Show Claude's internal reasoning before responses
  thinking_budget: 5000  # Maximum tokens for thinking (1000-10000)

# Context management strategy
context:
  # Number of most recent exchanges to always include in full
  immediate_exchanges: 3

  # Start summarizing when history exceeds this many exchanges
  summarize_after: 6

  # Always preserve the original question/prompt
  preserve_original: true

  # Create checkpoints at these intervals (turns)
  checkpoint_interval: 5

  # Maximum tokens to allow in context (approximate)
  max_context_tokens: 8000

  # Summarization strategy: "recursive" or "simple"
  summarization_strategy: "recursive"

# Display settings
display:
  # Mode: "single" (one terminal, alternating) or "dual" (coordinate two terminals)
  mode: "single"

  # Show token usage estimates
  show_tokens: true

  # Stats display mode: "simple", "detailed", or "geeky"
  # - simple: Basic token count and cost
  # - detailed: Adds model info and session stats
  # - geeky: Full technical breakdown with context window analysis
  stats_mode: "geeky"

  # Show context summary before each turn
  show_context_summary: false

  # Show timestamps
  show_timestamps: true

  # Use colors for agent names
  use_colors: true

  # Clear screen between turns (single mode only)
  clear_screen: false

# Logging settings
logging:
  # Save full conversation history
  save_full_history: true

  # Output format: "json" or "markdown"
  format: "json"

  # Output file path (relative to project root)
  output_file: "conversation_log.json"

  # Also save markdown transcript
  save_transcript: true
  transcript_file: "conversation_transcript.md"

  # Log level for debugging
  debug: false

# Web browsing capabilities (NEW!)
web_browsing:
  # Enable/disable web browsing for agents
  enabled: true

  # HTTP request settings
  timeout: 15  # Seconds to wait for page load
  user_agent: "ClaudeAgentChat/1.0 (Research Bot)"

  # Content extraction settings
  max_content_length: 100000  # Maximum characters from webpage
  include_metadata: true       # Include title and description
  extract_links: false         # Include links in content (not implemented yet)

  # Security and rate limiting
  max_urls_per_turn: 3  # Maximum URLs agent can fetch per turn

  # Domain filtering (empty = all allowed)
  allowed_domains: []   # e.g., ["wikipedia.org", "python.org"]

  # Blocked domains (for security/privacy)
  blocked_domains:
    - "facebook.com"
    - "twitter.com"
    - "instagram.com"
    - "tiktok.com"
    # Add more domains to block as needed
